Do not update the current environment
Since state_dir is set from TMPDIR and TMPDIR is set from state_dir,
the state_dir path is wrong when create_machine is called several time
in a test.

nixos.tests.installer.luksroot-format1.x86_64-linux was failing with:
      File "/nix/store/879x2vy6wbv9b5y910x106ccgkpwjggw-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 895, in create_socket
        s.bind(str(path))
    OSError: AF_UNIX path too long